credentials:
  usernames:
    admin:
      email: operaciones@translogisticla.com
      name: Admin
      password: $2b$12$TAKRqhIAnPNpV8p3b3i2xumYtGUQjpcZF0AxiEvturL4ReMsFoOCG
    apaz:
      email: comercial2@translogisticla.com
      name: Andres Paz
      password: $2b$12$hhco8uWR8JsQER3jG1wZiOM4svW1GNGGjdXMR1dVXdpfPt8og9c2.
    lpena:
      email: comercialclo@translogisticla.com
      name: Laura Peña
      password: $2b$12$CTA4qouAUxMIFtVJ9xL8h.xQdPPlG02vk0rJ5liq1YvxyFq8FRRYC
    dgaviria:
      email: dgaviria@translogisticla.com
      name: David Gaviria
      password: $2b$12$2qh1gJDOFSRfc8.oL3CJQ.ZSdPjNjmB0n70gjJMMRYUFaByowjLTm
    smartinez:
      email: gerencia@translogisticla.com
      name: Sergio Martinez
      password: $2b$12$vNe73awN9BneuJKJy6REk.wcouCMC3snVV6Eu/YfP5gf0fQ0V60ya
    sespitia:
      email: operaciones2@translogisticla.com
      name: Stefany Espitia
      password: $2b$12$UFuG0rFkmw7WIrX8HrYDve0so.B.zN.A4S1oWZsu.Yzk1AP3vnHsC

cookie:
  name: mylocaldata_cookie
  key: 4%£`r89O5Yda
  expiry_days: 30